# -----------------------------------
# CREATE NEW PROJECT INSIDE THIS ONE
# -----------------------------------

Write-Host ''
Write-Host ''
Write-Host '/---------------------------\' -ForegroundColor Magenta
Write-Host '| CREATE NEW PROJECT INSIDE |' -ForegroundColor Magenta
Write-Host '\---------------------------/' -ForegroundColor Magenta
Write-Host ''
Write-Host ''

# ----------------------------
# CREATING NEW CONSOLE PROJECT
# ----------------------------

Write-Host ''
Write-Host ' -> CREATE CONSOLE PROJECT ' -ForegroundColor Blue
Write-Host ''
Write-Host 'Enter the Project name (Ex: ProjectExample): ' -ForegroundColor White
$projectName = Read-Host '> '
dotnet new console -o $projectName # create the project on the Solution folder.

Write-Host ''
Write-Host '[OK]' -ForegroundColor Green -NoNewline
Write-Host ' Console Project Created Successfully!' -ForegroundColor White

# --------------------------------------------
# CONFIGURING THE PROJECTS INTO THE SOLUTION
# --------------------------------------------

Write-Host ' -> Configuring the projects inside the solution...' -ForegroundColor Yellow

dotnet sln add $projectName/$projectName.csproj # add the project into the solution.

Write-Host '[OK]' -ForegroundColor Green -NoNewline
Write-Host ' Project added into the solution!' -ForegroundColor White


# ------------------------------------
# GENERATION OF THE HELLO WORLD CODE
# ------------------------------------

Write-Host ' -> Creating a hello world template into the program.cs file...' -ForegroundColor Yellow
$code = @"
namespace $projectName
{
    public class Program
    {
      public static string GetHelloWorld()
      {
          return `"Hello World!`";
      }

      public static void Main(string[] args)
      {
          string test = GetHelloWorld();
          Console.WriteLine(test);
      }
    }
}
"@

$code | Out-File -FilePath $projectName/Program.cs

Write-Host '[OK]' -ForegroundColor Green -NoNewline
Write-Host ' Created the Hello World Template!' -ForegroundColor White

# ---------------------------------------
# TESTING THE PROJECT USING RUN COMMAND
# ---------------------------------------

Write-Host 'Running the project to validate the hello world!' -ForegroundColor Yellow

$projectCsproj = $projectName + '.csproj'
dotnet run --project $projectName/$projectCsproj

Write-Host '[OK]' -ForegroundColor Green -NoNewline
Write-Host ' Project runned Successfully!' -ForegroundColor White


Write-Host ''
Write-Host ' -> PROJECT CREATION COMPLETE! ' -ForegroundColor Magenta
Write-Host ''
Write-Host 'Script generated by: F4NT0 - Give a star in the https://github.com/F4NT0/CSharp-Template'

